name: storm
description: A Flutter App for fuel station management.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  bloc: ^9.2.1
  envied: ^1.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.1
  injectable: ^3.0.0
  intl: ^0.20.2
  sentry_flutter: ^9.24.0
  talker_bloc_logger: ^5.1.17
  talker_dio_logger: ^5.1.20
  talker_flutter: ^5.1.17

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  build_runner: ^2.15.0
  envied_generator: ^1.3.8
  flutter_gen_runner: ^5.14.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^3.0.2
  mocktail: ^1.0.5
  sentry_dart_plugin: ^3.4.0
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: ardin-biganiro
