#!/bin/bash

# This script can be used to run flutter test for a given directory.
# It will exclude generated code and translations (mimicking the ci) and 
# open the coverage report in a new window once it has run successfully.
#
# To run in main project:
# ./tool/coverage.sh
#
# To run in other directory:
# ./tool/coverage.sh ./path/to/other/project

set -e

# Resolve the target project path.
# Defaults to the current directory if no argument is given
PROJECT_PATH="${1:-.}"
# Path to the lcov coverage data file generated by flutter test
PROJECT_COVERAGE=./coverage/lcov.info

# Switch into the target project directory
cd "${PROJECT_PATH}"

# Remove any previous coverage output to ensure a clean run
rm -rf coverage

# Print the active Flutter version for traceability in CI logs
fvm flutter --version

# Run all tests with coverage enabled.
# - --exclude-coverage: strips generated and l10n files from the lcov report
# - --exclude-tags: skips tests tagged 'presubmit-only' (long-running / manual tests)
# - --test-randomize-ordering-seed: runs tests in a random order to catch order-dependent failures
very_good test --coverage --exclude-coverage "**/*.g.dart **/*.gen.dart **/l10n/*.dart **/l10n/**/*.dart **/main/bootstrap.dart" --exclude-tags 'presubmit-only' --test-randomize-ordering-seed random

# Strip generated and l10n files from the lcov data so they don't skew coverage numbers
lcov --ignore-errors unused --remove ${PROJECT_COVERAGE} -o ${PROJECT_COVERAGE} \
    '**/*.g.dart' \
    '**/l10n/*.dart' \
    '**/l10n/**/*.dart' \
    '**/main/bootstrap.dart' \
    '**/*.gen.dart'

# Generate an HTML report from the filtered lcov data and capture the summary output
genhtml ${PROJECT_COVERAGE} -o coverage | tee ./coverage/output.txt

# Extract the total-line coverage percentage from genhtml output.
COV_LINE=$(grep "lines\.\.\.\.\.\." ./coverage/output.txt | tail -1)

# Expected value indicating full coverage
SUB='100.0%'

# Check whether coverage reached 100% and report accordingly
if [[ "$COV_LINE" == *"$SUB"* ]]; then
    printf "\e[33;1m%s\e[0m\n" '[Coverage] All lines covered — coverage is 100%.'
else
    printf "\e[31;1m%s\e[0m\n" '[Coverage] Coverage is below 100% — open the HTML report to identify uncovered lines.'
    printf "\e[31;1m%s\e[0m\n" "Coverage summary: $COV_LINE"
    xdg-open ./coverage/index.html
fi